### ISSUE TITLE
Test error

### ISSUE THREAD

**Issue by kination** [Miserlou/NoDB#8]
I found some error while on test.
```
Traceback (most recent call last):
  File "/Users/kwangin/workspace/github_source/NoDB/tests/tests.py", line 56, in test_nodb
    nodb._deserialize(serialized)
  File "/Users/kwangin/workspace/github_source/NoDB/nodb/__init__.py", line 170, in _deserialize
    return_me['obj'] = pickle.loads(base64.b64decode(des_obj))
  File "/Users/kwangin/.pyenv/versions/3.5.1/lib/python3.5/base64.py", line 90, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
```
It looks like known one because it has been commented as `#python 3` in decoding line.
Is it right?

**Comment by Miserlou** [comment]
NoDB doesn't support Python3 right now, but if you want add support and send a PR, I'd gladly merge it!

**Comment by kination** [comment]
@Miserlou Okay! Is this test works well in python 2?

**Comment by Miserlou** [comment]
Yeah, it should all work fine on 2.7. NoDB was designed for AWS Lambda before it supported 36, so 36 support needs to be added to NoDB now.

**Comment by kination** [comment]
@Miserlou Okay. I'm looking on it.
